// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elyuvuzdpmzocftckomr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVseXV2dXpkcG16b2NmdGNrb21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDIxNDYsImV4cCI6MjA3MDkxODE0Nn0.DFsSoBRN3aAw4jz-aW83UNzbG2Q87h4VEhQUsmCfOeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});